### ISSUE TITLE
Can't compile, file "build" missing in /lib/modules/...

### ISSUE THREAD

**Issue by snigel** [mavam/ml-driver#5]
Raspberry pi2 running raspbian.

```
pi@raspberrypi2 ~/ml-driver $ make
make -C /lib/modules/4.1.18-v7+/build M=/home/pi/ml-driver modules
make[1]: *** /lib/modules/4.1.18-v7+/build: No such file or directory.  Stop.
Makefile:21: recipe for target 'default' failed
make: *** [default] Error 2
```

I do have files in the directory, but not build. Am I missing a package?

```
pi@raspberrypi2 ~/ml-driver $ ls -1 /lib/modules/4.1.18-v7+/
kernel
modules.alias
modules.alias.bin
modules.builtin
modules.builtin.bin
modules.dep
modules.dep.bin
modules.devname
modules.order
modules.softdep
modules.symbols
modules.symbols.bin
```

Edit: Found the solution. 
Generic solution: apt-get install linux-headers
For RPI with modern kernel:
http://raspberrypi.stackexchange.com/questions/43619/linux-headers-generic-package-not-found

**Comment by mavam** [comment]
Glad you figured it out. For the record: `apt-get-install linux-headers` installs the missing kernel includes.

**Comment by snigel** [comment]
Isn't that what I wrote?
"Generic solution: apt-get install linux-headers"

But for rpi, my issue was that the kernel-headers package was not available for my kernel. Same issue as in this thread:
http://raspberrypi.stackexchange.com/questions/43619/linux-headers-generic-package-not-found

**Comment by mavam** [comment]
> Isn't that what I wrote?

It is. I just wanted to summarize your insight at the bottom of this ticket, so that others who stumble across the same issue find the solution quickly.
